name: FR
version: 2.3.1
date: 23/02/2016
description: Computations with functionally recursive groups

authors:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

maintainers:
    - name: Laurent Bartholdi
      url: http://www.uni-math.gwdg.de/laurent

GAP: ">=4.7.6"

needed-pkgs:
    - name: "FGA"
      version: ">=1.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "Polycyclic"
      version: ">=2.2"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/polycyclic/"
    - name: "GAPDoc"
      version: ">=1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

suggested-pkgs:
    - name: "GBNP"
      version: ">=0.9"
      url: "http://mathdox.org/products/gbnp/"
    - name: "NQ"
      version: ">=2.4"
      url: "http://gap-system.github.io/nq/"
    - name: "NQL"
      version: ">=0.10"
      url: "http://www-public.tu-bs.de:8080/~y0019492/pub/nql/"

www: http://gap-packages.github.io/fr/
readme: http://gap-packages.github.io/fr/README.fr
packageinfo: http://gap-packages.github.io/fr/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/fr/releases/download/v2.3.1/fr-2.3.1.tar.gz

abstract: The <span class="pkgname">FR</span> package allows    GAP to manipulate groups generated by automata, and more generally    functionally recursive groups

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
